// This file will be generated by Supabase CLI
// Run: npx supabase gen types typescript --linked > src/lib/database.types.ts

export type Database = {
  // Placeholder - will be replaced with actual types
  public: {
    Tables: {
      projects: {
        Row: {
          id: string
          title: string
          slug: string
          description: string | null
          content: string | null
          thumbnail_url: string | null
          tags: string[] | null
          github_url: string | null
          demo_url: string | null
          featured: boolean
          created_at: string
        }
        Insert: {
          id?: string
          title: string
          slug: string
          description?: string | null
          content?: string | null
          thumbnail_url?: string | null
          tags?: string[] | null
          github_url?: string | null
          demo_url?: string | null
          featured?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          title?: string
          slug?: string
          description?: string | null
          content?: string | null
          thumbnail_url?: string | null
          tags?: string[] | null
          github_url?: string | null
          demo_url?: string | null
          featured?: boolean
          created_at?: string
        }
      }
      posts: {
        Row: {
          id: string
          title: string
          content: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          content: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          content?: string
          created_at?: string
          updated_at?: string
        }
      }
      contacts: {
        Row: {
          id: string
          name: string
          email: string
          message: string
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          email: string
          message: string
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          email?: string
          message?: string
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}

export type Project = Database['public']['Tables']['projects']['Row']
